name: Compile Latex and Release PDF  

on:
  push:
    tags:
      - 'v*'
    
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: src/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: main.pdf

